version: '3'

services:
  idp:
    build: ./IdP
    ports:
     - "443:443"

  rp:
    build: ./RP
    ports:
     - "8000:8000"
    links:
     - claims_provider
     - idp

  claims_provider:
    build: ./claims_provider
    ports:
     - "5000:5000"
    links:
     - elixir_rems_proxy

  elixir_rems_proxy:
    build: ./elixir_rems_proxy
    depends_on:
     - postgres
    restart: always
    ports:
     - "8080:8080"
    links:
     - postgres
    environment:
      - DB_HOST=postgresql://postgres:5432
      - PUBLIC_KEY=secret

  postgres:
    build: ./postgres_test_data
    ports:
     - "5432:5432"
